FROM python:3.7.8-slim

COPY required.txt
RUN pip install -U pip && pip install -r required.txt

COPY ./app /app/fc572
COPY ./bin /app/bin
COPY wsgi.py /app/wsgi.py
WORKDIR /app

RUN useradd demo
USER demo

EXPOSE 8080

ENTRYPOINT ["bash", "/app/bin/run.sh"]